#169: Support in memory zip files in the schema validation api
RESOStandards/reso-certification-utils pull request #170
Opened 2024-08-12 11:17 UTC by mohit-s96

closes #169

2024-08-20 21:17 UTC, darnjo requested changes

2024-08-20 21:17 UTC, darnjo commented on lib/schema/validate.js
> +    Object.entries(payload).forEach(([fileName, payload]) => {
`payload` might not be defined here and the `forEach` could fail.

2024-08-20 21:17 UTC, darnjo commented on lib/schema/validate.js
>    resourceName = 'Property',
`resourceName` should not default to string here. If no value is provided and `resourceName` is required, then an error should be thrown.

2024-08-20 21:17 UTC, darnjo commented on common.js
> +  const readZip = pathOrBuffer instanceof Buffer ? yauzl.fromBuffer : yauzl.open;
Some checking should be done that this is either a buffer or path before trying to open it. If not, then an error should be thrown.

2024-08-20 21:17 UTC, darnjo commented on common.js
> +    readZip(pathOrBuffer, { lazyEntries: true }, function (err, zipfile) {
Do you need access to an inner `this` instance? Otherwise, I think this can be an arrow function?

2025-07-23 19:14 UTC, darnjo commented
This code should be manually copied into the `v3.0.0` branch (not cherry-picked) and a PR should be made against that branch.

2025-08-01 15:54 UTC, mohit-s96 commented
closing in favor of https://github.com/RESOStandards/reso-certification-utils/pull/225

2025-08-01 15:54 UTC, closed without merging